sudo: required
language: java
jdk: oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_STG=<YOUR_PROJECT_NAME>
    - CLUSTER_NAME_STG=<YOUR_CLUSTER_NAME>
    - PROJECT_NAME_PRD=<YOUR_PROJECT_NAME>
    - CLUSTER_NAME_PRD=<YOUR_CLUSTER_NAME>
    - CLOUDSDK_COMPUTE_ZONE=<YOUR_GCLOUD_COMPUTE_ZONE>
    - DOCKER_IMAGE_NAME=appexample
    - KUBE_DEPLOYMENT_NAME=appexample
    - KUBE_DEPLOYMENT_CONTAINER_NAME=appexample
    - NODE_ENV=CI

script:
  - gradle clean
  - gradle wrapper
  - ./gradlew build

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
#  - echo 'download google cloud sdk'
#  - echo '==========================================='
#  - echo 'google cloud version'
#  - gcloud --quiet version
#  - gcloud --quiet components update
#  - gcloud --quiet components beta update
#  - gcloud --quiet components update kubectl
#  - echo '==========================================='

deploy:
  - provider: script
    script: sh ./scripts/deploy-staging.sh
    skip_cleanup: true
    on:
      branch: master
