sudo: required
language: java
jdk: oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script:
  - gradle clean
  - gradle wrapper
  - ./gradlew build

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
#  - echo 'download google cloud sdk'
#  - echo '==========================================='
#  - echo 'google cloud version'
#  - gcloud --quiet version
#  - gcloud --quiet components update
#  - gcloud --quiet components beta update
#  - gcloud --quiet components update kubectl
#  - echo '==========================================='

deploy:
  - provider: script
    script: sh ./scripts/deploy-staging.sh
    skip_cleanup: true
    on:
      all_branches: true
#      branch: master
